---
title: "My English Activity Log"
author:
  - name: Némo Lemaire
date: 09-16-2019
categories:
  - M.E.A.L.
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Date to date:

26/11/2019: I watched a bunch of podcast from BBC (got a bit carried away), here's some of them: "**Meet the World's Tiniest Trees! | From Plant to Planet with Nellie Nilsen | BBC Earth**" (<https://www.youtube.com/watch?v=7-_C1WaCnno>), "**Weirdest Animal Relationships | Top 5 | BBC Earth**" (<https://www.youtube.com/watch?v=s9KvEg102Tc>), "**The deadly tentacles of the Portuguese man o' war | Blue Planet II - BBC One**" (<https://www.youtube.com/watch?v=gr1ps0ooDhU>), "**Hungry Venus flytraps snap shut on a host of unfortunate flies | Life - BBC**" (<https://www.youtube.com/watch?v=O7eQKSf0LmY>)

25/11/2019: I watched a video about the "Pygmalion effect" (<https://www.youtube.com/watch?v=4aN5TbGW5JA>); to put it simply this psychological phenomena explain how the belief of others about us can affect our expectation and thus modifying their belief in consequence wich will then reaffect us, and so on.
 I also watched two videos from TE-Ed, the first one was about the history of chess and the second one the history of corn.

24/11/2019: I have started a new book: "The Charlemagne Pursuit". For what I have already read this thriller is about a former secret service agent, the mystery surrounding is father death, governement conspiracies and Charlemagne? The thematic of this book seems quite similar,in a certain way, to the thrillers written by Dan Brown (author of "The Da Vinci Code", "Angel & Demon").

09/11/2019: I nearly finished rereading "Norse Mythology" from Neil Gaiman. As I remembered the books is really interesting, the writter took inspiration from two olds translations: "Prose Edda" and "Poetic Edda" (respectivly written in the  XIII century). The last chapter that I read was about Loki's children and how their presence at the end of everything will bring demise to the gods.

# Right to the point:
## Films:
- "Pulp fiction", Quentin Tarantino, 1994
- "Inglourious Basterds", Quentin Tarantino, 2009
- "Fear and Loathing in Las Vegas", Terry Gilliam, 1998

## TV series:
- "Doctor Who"
- "Sherlock Holmes"

## Podcasts:
- "World War Ant", Kurzgesagt
- "Ant Megacolony", Kurzgesagt
- "Angry Video Game Nerd", Cinemassacre
- Channel awesome
- "By the way, can you...", DanPlan
- Mythology & Fiction Explained
- Scott The Woz
- TED-Ed
- Sprouts
- BBC Earth

## Books:
- "Alice in wonderland", Lewis Carroll, 1865
- "Tales of Mystery and Imagination", Edgar Allan Poe
- "The prophecy", Chris Kuzneski
- "Norse mytology", Neil Gaiman
- "Breverton's phantasmgoria; a compendium of monsters, myths and legends",Terry Breverton
- "The Charlemagne Pursuit", Steve Berry

## Magazines:

## Games:
- "Danganronpa 1-2 reloaded", Spike Chunsoft
- "Odin sphere leifthrasir", Atlus

## Outdoor events:

