---
title: "article-6: Bats inspire detectors to help prevent oil and gas pipe leaks"
author:
  - name: Némo Lemaire
date: 02-09-2020
categories: 
preview:
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<iframe width="560" height="315" src="https://www.youtube.com/embed/kp5jyZtoTIg" frameborder="0" allowfullscreen></iframe>


## Article (URL) and word count

* URL of the article: <https://phys.org/news/2020-01-detectors-oil-gas-pipe-leaks.html> (30 January 2020)

* Word: 665

## Vocabulary 

| Words from the text | Synonym/explanation in English | Translation in French|
| ------------------- | ------------------------------ |------------|
| Insulation | - / The act of covering something to stop heat, sound, or electricity from escaping. | Isolation |
| Frigid | polar / Extremely cold. | Glacial |
| Template | device / A system that can be copied by other. | Modèle |
| To lock in | seal in / To keep inside, without allowing it to escape. | Verrouiller |
| Insulator | nonconductor / A material from which heat or electricity cannot escape. | Isolant |
|  To scale | - / To reproduce something at a greater or lower scale. | Produire à une plus grande ou plus petite échelle |
| Aerogel | frozen smoke / A solid material (of extremely low density) produced by removing the liquid component from a conventional gel. | aérogel |
| Analogous | akin / That have similar features. | Analogue |
| Hollow | empty / An empty space inside something. | Creux |
| Core | interior / The center of something | Noyau |
| Coats | fur / The hair that cover an animal's body. | Pelage |
| Outstanding | incredible / Excellent | Exceptionnel |
| To emulate | to imitate / To imitate something in order to mimic its properties. | Imiter |
| Strand of hair | Thread of hair / A single piece of hair. | Mèche de cheveux |
| To wind | to coil / To twist something around something else. | Enrouler |
| Heat flow | thermal flux  / Thermic energy (heat) that flows trough one's body, allowing its temperature to stay constant (in the case of homeotherms organisms). | Flux thermique |
| Hardly | rarely / Nearly never. | Rarement |
| Relevant | appropriate / Appropriate with the current thematic, goal. | Pertinent |

## Analysis table

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |  |
| Published in?                |  |
| General topic?               |  |
| Procedure/what was examined? |  |
| Conclusions/discovery?       |  |
| Remaining questions?         |  |

